name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.2

      - name: Install Dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm eslint src

      - name: Build & Compile
        run: pnpm build --verbose
